defmodule FavnReferenceWorkload.Warehouse.Landing do
  @moduledoc "Compact JSON landing files generated by the local CRM demo."

  use Favn.Namespace

  meta(owner: "generic-crm-demo", tags: [:landing, :local])
end
