CREATE ROLE favn_runtime
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  PASSWORD 'favn_runtime_local';

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE favn_dev FROM PUBLIC;
GRANT CONNECT ON DATABASE favn_dev TO favn_runtime;
