# Historical warning baseline generated with the CI-pinned Elixir/OTP toolchain.
# Remove entries when debt is fixed; do not regenerate this file to accept new warnings.
[
  {"lib/favn/sql_asset.ex", "Function contract_compile_error!/3 has no local return."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :forbidden | :unauthenticated}."},
  {"lib/favn_orchestrator.ex", "Function operator_backfill_opts/3 will never be called."},
  {"lib/favn_orchestrator.ex", "Function operator_refresh/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function execution_group_status/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function merge_coverage_metadata/2 will never be called."},
  {"lib/favn_orchestrator.ex",
   "Function remaining_retry_plan_fingerprint/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function begin_operator_command/8 will never be called."},
  {"lib/favn_orchestrator.ex", "Function idempotency_key_opts/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function put_rebuild_plan_idempotency/2 will never be called."},
  {"lib/favn_orchestrator.ex",
   "Function put_rebuild_command_idempotency/2 will never be called."},
  {"lib/favn_orchestrator.ex", "Function run_command_opts/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function finish_operator_result/8 will never be called."},
  {"lib/favn_orchestrator.ex", "Function finish_operator_audit/9 will never be called."},
  {"lib/favn_orchestrator.ex", "Function operator_error_code/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function admin?/1 will never be called."},
  {"lib/favn_orchestrator/api/actors_router.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_credentials | :unauthenticated}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_session | :unauthenticated}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type \n  {:error,\n   :service_unauthorized | :unauthenticated | {:missing_field, <<_::64, _::size(40)>>}}\n."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :service_unauthorized | :unauthenticated | {:missing_field, <<_::104>>}}."},
  {"lib/favn_orchestrator/api/auth_router.ex", "Function audit/5 will never be called."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "Function persistence_roles/1 will never be called."},
  {"lib/favn_orchestrator/api/coverage_router.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_orchestrator/api/coverage_router.ex",
   "Function audit_submit/8 will never be called."},
  {"lib/favn_orchestrator/api/operator_commands.ex",
   "The function call normalize_run_input will not succeed."},
  {"lib/favn_orchestrator/api/operator_commands.ex",
   "Function submit_operator_run/5 will never be called."},
  {"lib/favn_orchestrator/api/runs_router.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/api/runs_router.ex", "The pattern can never match the type true."},
  {"lib/favn_orchestrator/api/runs_router.ex",
   "The pattern can never match the type \n  {:error,\n   :invalid_manifest_selection\n   | :invalid_target\n   | {:manifest_filter_lookup_failed, _}\n   | {:unsupported_retry_option, atom(), :use_retry_policy}\n   | %FavnOrchestrator.Persistence.Error{\n       :details => map(),\n       :kind =>\n         :conflict\n         | :constraint\n         | :fenced\n         | :forbidden\n         | :internal\n         | :invalid\n         | :limit_exceeded\n         | :not_found\n         | :timeout\n         | :unavailable\n         | :unsupported,\n       :message => binary(),\n       :retryable? => boolean()\n     }}\n."},
  {"lib/favn_orchestrator/auth.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/auth.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/auth.ex",
   "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/auth.ex", "The function call set_membership will not succeed."},
  {"lib/favn_orchestrator/auth/store.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/diagnostics.ex",
   "The pattern can never match the type \n  {:error,\n   %FavnOrchestrator.Persistence.Error{\n     :details => map(),\n     :kind =>\n       :conflict\n       | :constraint\n       | :fenced\n       | :forbidden\n       | :internal\n       | :invalid\n       | :limit_exceeded\n       | :not_found\n       | :timeout\n       | :unavailable\n       | :unsupported,\n     :message => binary(),\n     :retryable? => boolean()\n   }}\n  | {:ok,\n     %FavnOrchestrator.Persistence.Diagnostics{\n       :backend => atom(),\n       :engine => map(),\n       :features => nil | map(),\n       :metadata => map(),\n       :pool => nil | map(),\n       :schema => map()\n     }}\n."},
  {"lib/favn_orchestrator/execution_admission.ex", "The pattern can never match the type :ok."},
  {"lib/favn_orchestrator/operator/catalogue/targets.ex",
   "The pattern pattern \#{'module':=_module@1} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/commands.ex",
   "The pattern pattern <__opts@1, __metadata@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/schedules.ex",
   "The pattern pattern <__window@1, __due_at@1, __timezone@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/persistence/operator_read_store.ex",
   "Unknown type: FavnOrchestrator.Persistence.Results.CursorPage.t/0."},
  {"lib/favn_orchestrator/persistence/queries/operator_reads.ex",
   "Unknown type: FavnOrchestrator.Persistence.Results.CursorPage.t/0."},
  {"lib/favn_orchestrator/resource_recovery.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/run_manager/submission_builder.ex",
   "The pattern pattern \#{'__struct__':='Elixir.FavnOrchestrator.RunState'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_read_model.ex",
   "Invalid type specification for function from_operator_run_overview."},
  {"lib/favn_orchestrator/run_read_model.ex", "Unknown type: BackfillWindow.status/0."},
  {"lib/favn_orchestrator/run_read_model.ex",
   "The pattern can never match the type _, _, :operator."},
  {"lib/favn_orchestrator/run_read_model.ex",
   "The pattern can never match the type \n  %FavnOrchestrator.RunState{:status => _, _ => _},\n  :asset | :backfill_child | :pipeline | :rerun,\n  nil\n."},
  {"lib/favn_orchestrator/run_read_model.ex", "The pattern can never match the type _, false."},
  {"lib/favn_orchestrator/run_read_model.ex", "Function window_progress/1 will never be called."},
  {"lib/favn_orchestrator/run_read_model.ex", "Function count_status/2 will never be called."},
  {"lib/favn_orchestrator/run_read_model/step_projection.ex",
   "The guard clause can never succeed."},
  {"lib/favn_orchestrator/run_read_model/step_projection.ex",
   "The pattern variable __run@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_retry_planner.ex",
   "The pattern pattern <_context@1, __run@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_retry_planner.ex",
   "The pattern variable __run@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "The pattern can never match the type :terminal."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "Function schedule_retry/2 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "The pattern variable __ctx@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/freshness/asset_freshness_state_codec.ex",
   "The guard clause can never succeed."},
  {"lib/favn_orchestrator/storage/freshness/asset_freshness_state_codec.ex",
   "The pattern variable _input_versions@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/materialization_claim_codec.ex",
   "The guard clause can never succeed."},
  {"lib/favn_orchestrator/storage/run_query.ex",
   "The pattern pattern <__value@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/run_snapshot_codec.ex",
   "The pattern variable _metadata@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/run_snapshot_codec.ex",
   "The pattern variable _result@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/transition_writer.ex",
   "The pattern pattern <\#{'__struct__':='Elixir.FavnOrchestrator.RunEvent'}, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_storage_postgres/backfills/store.ex", "The pattern can never match the type true."},
  {"lib/favn_storage_postgres/runs/decoder.ex",
   "Unknown type: FavnStoragePostgres.Schemas.Run.t/0."},
  {"lib/favn_storage_postgres/runs/decoder.ex",
   "The pattern can never match the type \n  {:error,\n   %FavnOrchestrator.Persistence.Error{\n     :details => map(),\n     :kind =>\n       :conflict\n       | :constraint\n       | :fenced\n       | :forbidden\n       | :internal\n       | :invalid\n       | :limit_exceeded\n       | :not_found\n       | :timeout\n       | :unavailable\n       | :unsupported,\n     :message => binary(),\n     :retryable? => boolean()\n   }}\n."},
  {"lib/favn_storage_postgres/runs/decoder.ex", "The function call decode_run will not succeed."},
  {"lib/favn_storage_postgres/runs/store.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_storage_postgres/runs/store.ex",
   "The pattern can never match the type \n  {:error,\n   %FavnOrchestrator.Persistence.Error{\n     :details => map(),\n     :kind =>\n       :conflict\n       | :constraint\n       | :fenced\n       | :forbidden\n       | :internal\n       | :invalid\n       | :limit_exceeded\n       | :not_found\n       | :timeout\n       | :unavailable\n       | :unsupported,\n     :message => binary(),\n     :retryable? => boolean()\n   }}\n."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type {:error, :backend_unavailable}."},
  # Everything `asset_from_detail/2` reaches. Dialyzer cannot see that a LiveView
  # `render/1` calls it, so the whole chain below it reads as unreachable.
  {"lib/favn_view/asset_detail_live.ex", "Function asset_from_detail/2 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function run_context_path/2 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function asset_name/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function run_entry/2 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function window_entry_label/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function cadence_label/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function cadence_word/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function window_field/2 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function duration_label/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex",
   "Function missing_freshness_detail/0 will never be called."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/asset_detail_live.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_view/asset_run_logs_live.ex", "The guard clause can never succeed."},
  {"lib/favn_view/auth/scope.ex", "The function call get will not succeed."},
  {"lib/favn_view/controllers/operator_session_controller.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_view/logs_live_support.ex", "Function target_label/1 will never be called."},
  {"lib/favn_view/logs_live_support.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/logs_live_support.ex",
   "Function run_context_from_public/2 will never be called."},
  {"lib/favn_view/logs_live_support.ex",
   "Function asset_context_from_public/1 will never be called."},
  {"lib/favn_view/logs_live_support.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "Function normalize_window_kind/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "The pattern can never match the type {:error, :backend_unavailable}."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "Function pipeline_from_detail/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "The pattern can never match the type nil."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_kind/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_timezone/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function pipeline_name/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "Function dependencies_label/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_label/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_label/2 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function status_label/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function last_run_label/1 will never be called."},
  {"lib/favn_view/plugs/trusted_proxy_headers.ex",
   "The pattern variable __unknown_peer@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_view/run_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/run_detail_live.ex",
   "Function retry_remaining_submitted_label/2 will never be called."},
  {"lib/favn_view/run_detail_live.ex",
   "Function retry_remaining_partial_label/2 will never be called."},
  {"lib/favn_view/run_detail_live.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/mix/tasks/favn.postgres.maintenance.ex", "Function usage!/0 has no local return."},
  {"lib/mix/tasks/favn.postgres.provision_workspace.ex", "Function usage!/0 has no local return."}
]
