# Historical warning baseline generated with the CI-pinned Elixir/OTP toolchain.
# Remove entries when debt is fixed; do not regenerate this file to accept new warnings.
[
  {"lib/favn/assets/planner.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/assets/planner.ex", "Type mismatch in call with opaque term in walk_upstream."},
  {"lib/favn/circuit_breaker/policy.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/dev/build/control_plane_inputs.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/dev/build/control_plane_inputs.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/dev/build/control_plane_inputs.ex", "Type mismatch in call with opaque term in resolve_lock_closure."},
  {"lib/favn/dev/build/runner_inputs.ex", "Type mismatch in call without opaque term in difference."},
  {"lib/favn/dev/build/runner_inputs.ex", "Type mismatch in call without opaque term in to_list."},
  {"lib/favn/dev/build/runner_inputs.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/dev/build/runner_inputs.ex", "Type mismatch in call with opaque term in expand_dependency_graph."},
  {"lib/favn/dev/compose_lifecycle.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function do_start/5 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function release_operations/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function deploy_manifest/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function do_deploy_manifest/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function coordinated_runner_replacement/4 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function safely_replace_runner/6 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function replace_runner/6 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function do_replace_runner/6 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function await_runner_drain/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function do_await_runner_drain/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function retry_runner_drain/4 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function ensure_no_in_flight_runs/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function fetch_in_flight_runs/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function ensure_empty_run_ids/1 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function begin_runner_replacement/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function runner_replacement_status/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function finish_runner_replacement/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function verify_replacement_runner/4 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function maintenance_drained?/1 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function mark_recovery_active/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function verify_unchanged_previous_runner/5 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function restore_previous_runner/5 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function verify_active_manifest_alignment/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function replacement_failure/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function previous_runner_from_recovery/1 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function apply_prepared_reload/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function apply_recoverable_reload/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function await_readiness/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function reload_preflight/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function await_liveness/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function do_await_liveness/4 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function do_await_readiness/4 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function classify_reload/4 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function apply_runner_change/5 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function service_token/1 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function client/1 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function ensure_reload_recovery/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function new_recovery/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function active_manifest_identity/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function fetch_active_manifest_identity/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function maintenance_token/0 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "The pattern can never match the type :runner."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function ensure_startable_stack/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function cleanup_failed_start/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function write_runtime/6 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function update_runtime_after_reload/6 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function unchanged_deployment/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function remove_obsolete_generated_compose/2 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function start_result/3 will never be called."},
  {"lib/favn/dev/compose_lifecycle.ex", "Function reload_message/3 will never be called."},
  {"lib/favn/dev/doctor.ex",
   "The pattern variable _error@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/dev/doctor.ex",
   "The pattern variable __key@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/dev/install.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/dev/orchestrator_client.ex",
   "The pattern variable __session_context@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/dev/runner_image.ex",
   "The pattern variable _output@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/freshness/key.ex",
   "The pattern can never match the type binary() | {integer(), integer()}, binary() | {integer(), integer()}."},
  {"lib/favn/manifest/rehydrate.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/manifest/serializer.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/manifest/serializer.ex", "Type mismatch in call with opaque term in normalize_value."},
  {"lib/favn/resource_recovery/policy.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/sql/adapter/duckdb.ex", "The guard clause can never succeed."},
  {"lib/favn/sql/adapter/duckdb/adbc.ex", "The guard clause can never succeed."},
  {"lib/favn/sql/adapter/duckdb/adbc/bootstrap.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/favn/sql/adapter/duckdb/bootstrap.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/favn/sql/client.ex", "The guard clause can never succeed."},
  {"lib/favn/sql/client.ex",
   "The pattern pattern <_operation@1, __opts@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn/sql/contract.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/sql/retry.ex", "The guard clause can never succeed."},
  {"lib/favn/sql_asset.ex", "Function contract_compile_error!/3 has no local return."},
  {"lib/favn/sql_asset/relation_usage.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/favn/sql_asset/relation_usage.ex", "Type mismatch in call with opaque term in collect_runtime_relations."},
  {"lib/favn/sql_asset/runtime.ex",
   "The pattern pattern \#{'__struct__':='Elixir.Favn.SQLAsset.Definition'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn/sql_asset/runtime.ex",
   "The pattern variable __refs@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn/sql_asset/runtime.ex",
   "The pattern can never match the type {:error, _}, {_, _}, :explain | :materialize | :preview."},
  {"lib/favn/sql_client.ex",
   "The pattern pattern \#{'__struct__':='Elixir.Favn.RelationRef'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_orchestrator.ex", "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator.ex", "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator.ex", "The pattern can never match the type {:error, :forbidden | :unauthenticated}."},
  {"lib/favn_orchestrator.ex", "Function operator_backfill_opts/3 will never be called."},
  {"lib/favn_orchestrator.ex", "Function operator_refresh/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function execution_group_status/1 will never be called."},
  {"lib/favn_orchestrator.ex",
   "The pattern variable __module@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator.ex",
   "The pattern variable _value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/api/actors_router.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_credentials | :unauthenticated}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_session | :unauthenticated}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type \n  {:error,\n   :service_unauthorized | :unauthenticated | {:missing_field, <<_::64, _::size(40)>>}}\n."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :service_unauthorized | :unauthenticated | {:missing_field, <<_::104>>}}."},
  {"lib/favn_orchestrator/api/auth_router.ex", "Function audit/5 will never be called."},
  {"lib/favn_orchestrator/api/auth_router.ex", "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/api/auth_router.ex", "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/api/auth_router.ex", "Function persistence_roles/1 will never be called."},
  {"lib/favn_orchestrator/api/authentication.ex", "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/api/operator_commands.ex", "The function call normalize_run_input will not succeed."},
  {"lib/favn_orchestrator/api/operator_commands.ex", "Function submit_operator_run/5 will never be called."},
  {"lib/favn_orchestrator/api/runs_router.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/api/runs_router.ex", "The pattern can never match the type true."},
  {"lib/favn_orchestrator/api/runs_router.ex",
   "The pattern can never match the type \n  {:error,\n   :invalid_manifest_selection\n   | :invalid_target\n   | {:manifest_filter_lookup_failed, _}\n   | {:unsupported_retry_option, atom(), :use_retry_policy}\n   | %FavnOrchestrator.Persistence.Error{\n       :details => map(),\n       :kind =>\n         :conflict\n         | :constraint\n         | :fenced\n         | :forbidden\n         | :internal\n         | :invalid\n         | :limit_exceeded\n         | :not_found\n         | :timeout\n         | :unavailable\n         | :unsupported,\n       :message => binary(),\n       :retryable? => boolean()\n     }}\n."},
  {"lib/favn_orchestrator/api/runs_router.ex",
   "The pattern can never match the type \n  {:manifest_filter_lookup_failed, _}\n  | {:unsupported_retry_option, atom(), :use_retry_policy}\n  | %FavnOrchestrator.Persistence.Error{\n      :details => map(),\n      :kind =>\n        :conflict\n        | :constraint\n        | :fenced\n        | :forbidden\n        | :internal\n        | :invalid\n        | :limit_exceeded\n        | :not_found\n        | :timeout\n        | :unavailable\n        | :unsupported,\n      :message => binary(),\n      :retryable? => boolean()\n    }\n."},
  {"lib/favn_orchestrator/auth.ex", "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/auth.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/auth.ex", "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/auth.ex", "The function call set_membership will not succeed."},
  {"lib/favn_orchestrator/auth/store.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/auth/store.ex",
   "The pattern can never match the type {:error, :invalid_session | :not_cached}."},
  {"lib/favn_orchestrator/auth/store.ex", "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/auth/store.ex", "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/auth/store.ex", "The function call set_membership will not succeed."},
  {"lib/favn_orchestrator/diagnostics.ex",
   "The pattern can never match the type \n  {:error,\n   %FavnOrchestrator.Persistence.Error{\n     :details => map(),\n     :kind =>\n       :conflict\n       | :constraint\n       | :fenced\n       | :forbidden\n       | :internal\n       | :invalid\n       | :limit_exceeded\n       | :not_found\n       | :timeout\n       | :unavailable\n       | :unsupported,\n     :message => binary(),\n     :retryable? => boolean()\n   }}\n  | {:ok,\n     %FavnOrchestrator.Persistence.Diagnostics{\n       :backend => atom(),\n       :engine => map(),\n       :features => nil | map(),\n       :metadata => map(),\n       :pool => nil | map(),\n       :schema => map()\n     }}\n."},
  {"lib/favn_orchestrator/execution_admission.ex", "The pattern can never match the type :ok."},
  {"lib/favn_orchestrator/operator/catalogue.ex",
   "The pattern pattern \#{'__struct__':='Elixir.Favn.Manifest.Version'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/catalogue.ex",
   "The pattern variable __asset_ref@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/catalogue/targets.ex",
   "The pattern pattern \#{'module':=_module@1} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/catalogue/timeline.ex", "Type mismatch in call without opaque term in size."},
  {"lib/favn_orchestrator/operator/commands.ex",
   "The pattern pattern <__opts@1, __metadata@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/schedules.ex",
   "The pattern pattern <__window@1, __due_at@1, __timezone@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/operator/schedules.ex",
   "The pattern can never match the type \n  %FavnOrchestrator.SchedulerEntry{\n    :activation_state => :enabled,\n    :active => true,\n    :cron => nil | binary(),\n    :effective_enabled? => true,\n    :in_flight_run_id => nil | binary(),\n    :last_due_at =>\n      nil\n      | %DateTime{\n          :calendar => atom(),\n          :day => pos_integer(),\n          :hour => non_neg_integer(),\n          :microsecond => {_, _},\n          :minute => non_neg_integer(),\n          :month => pos_integer(),\n          :second => non_neg_integer(),\n          :std_offset => integer(),\n          :time_zone => binary(),\n          :utc_offset => integer(),\n          :year => integer(),\n          :zone_abbr => binary()\n        },\n    :last_evaluated_at =>\n      nil\n      | %DateTime{\n          :calendar => atom(),\n          :day => pos_integer(),\n          :hour => non_neg_integer(),\n          :microsecond => {_, _},\n          :minute => non_neg_integer(),\n          :month => pos_integer(),\n          :second => non_neg_integer(),\n          :std_offset => integer(),\n          :time_zone => binary(),\n          :utc_offset => integer(),\n          :year => integer(),\n          :zone_abbr => binary()\n        },\n    :last_scheduler_error =>\n      nil\n      | %FavnOrchestrator.SchedulerError{\n          :code => atom() | binary(),\n          :message => binary(),\n          :occurred_at => map(),\n          :phase => :compute_due | :evaluate | :persist_state | :submit_run\n        },\n    :last_submitted_due_at =>\n      nil\n      | %DateTime{\n          :calendar => atom(),\n          :day => pos_integer(),\n          :hour => non_neg_integer(),\n          :microsecond => {_, _},\n          :minute => non_neg_integer(),\n          :month => pos_integer(),\n          :second => non_neg_integer(),\n          :std_offset => integer(),\n          :time_zone => binary(),\n          :utc_offset => integer(),\n          :year => integer(),\n          :zone_abbr => binary()\n        },\n    :manifest_content_hash => nil,\n    :manifest_version_id => binary(),\n    :missed => atom(),\n    :next_due_at =>\n      nil\n      | %DateTime{\n          :calendar => atom(),\n          :day => pos_integer(),\n          :hour => non_neg_integer(),\n          :microsecond => {_, _},\n          :minute => non_neg_integer(),\n          :month => pos_integer(),\n          :second => non_neg_integer(),\n          :std_offset => integer(),\n          :time_zone => binary(),\n          :utc_offset => integer(),\n          :year => integer(),\n          :zone_abbr => binary()\n        },\n    :overlap => atom(),\n    :pipeline_module => atom(),\n    :queued_due_at =>\n      nil\n      | %DateTime{\n          :calendar => atom(),\n          :day => pos_integer(),\n          :hour => non_neg_integer(),\n          :microsecond => {_, _},\n          :minute => non_neg_integer(),\n          :month => pos_integer(),\n          :second => non_neg_integer(),\n          :std_offset => integer(),\n          :time_zone => binary(),\n          :utc_offset => integer(),\n          :year => integer(),\n          :zone_abbr => binary()\n        },\n    :runtime_state => :idle | :queued | :running,\n    :schedule_fingerprint => nil | binary(),\n    :schedule_id => atom(),\n    :timezone => nil | binary(),\n    :updated_at =>\n      nil\n      | %DateTime{\n          :calendar => atom(),\n          :day => pos_integer(),\n          :hour => non_neg_integer(),\n          :microsecond => {_, _},\n          :minute => non_neg_integer(),\n          :month => pos_integer(),\n          :second => non_neg_integer(),\n          :std_offset => integer(),\n          :time_zone => binary(),\n          :utc_offset => integer(),\n          :year => integer(),\n          :zone_abbr => binary()\n        },\n    :window =>\n      nil\n      | %Favn.Window.Policy{\n          :allow_full_load => boolean(),\n          :anchor => :current_period | :previous_complete_period,\n          :kind => :day | :hour | :month | :year,\n          :timezone => nil | binary()\n        }\n  },\n  _,\n  :invalid_date\n  | :invalid_time\n  | :invalid_window_bounds\n  | nil\n  | {:duplicate_opt\n     | :invalid_anchor_policy\n     | :invalid_datetime\n     | :invalid_kind\n     | :invalid_opts\n     | :invalid_period_count\n     | :invalid_period_kind\n     | :invalid_timezone\n     | :unknown_opt, _}\n  | {:invalid_boolean, :allow_full_load, _}\n."},
  {"lib/favn_orchestrator/operator/schedules.ex", "The test true == false can never evaluate to 'true'."},
  {"lib/favn_orchestrator/operator/schedules.ex", "The test :enabled == :needs_review can never evaluate to 'true'."},
  {"lib/favn_orchestrator/persistence/operator_read_store.ex",
   "Unknown type: FavnOrchestrator.Persistence.Results.CursorPage.t/0."},
  {"lib/favn_orchestrator/persistence/queries/operator_reads.ex",
   "Unknown type: FavnOrchestrator.Persistence.Results.CursorPage.t/0."},
  {"lib/favn_orchestrator/production_runtime_config.ex",
   "The pattern can never match the type \n  0 | 1 | 100 | 1000 | 65536 | 1_048_576 | 67_108_864,\n  200\n  | 30000\n  | 65535\n  | 100_000\n  | 120_000\n  | 300_000\n  | 2_592_000\n  | 3_600_000\n  | 8_388_608\n  | 33_554_432\n  | 86_400_000\n  | 134_217_728\n  | 8_589_934_592\n."},
  {"lib/favn_orchestrator/resource_recovery.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/run_manager/submission_builder.ex",
   "The pattern pattern \#{'__struct__':='Elixir.FavnOrchestrator.RunState'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_read_model.ex", "Invalid type specification for function from_operator_run_overview."},
  {"lib/favn_orchestrator/run_read_model.ex", "Unknown type: BackfillWindow.status/0."},
  {"lib/favn_orchestrator/run_read_model.ex", "The pattern can never match the type _, _, :operator."},
  {"lib/favn_orchestrator/run_read_model.ex",
   "The pattern can never match the type \n  %FavnOrchestrator.RunState{:status => _, _ => _},\n  :asset | :backfill_child | :pipeline | :rerun,\n  nil\n."},
  {"lib/favn_orchestrator/run_read_model.ex", "The pattern can never match the type _, false."},
  {"lib/favn_orchestrator/run_read_model.ex", "Function window_progress/1 will never be called."},
  {"lib/favn_orchestrator/run_read_model.ex", "Function count_status/2 will never be called."},
  {"lib/favn_orchestrator/run_read_model/step_projection.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/run_read_model/step_projection.ex",
   "The pattern variable __run@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_retry_planner.ex",
   "The pattern pattern <_context@1, __run@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_retry_planner.ex",
   "The pattern variable __run@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_server.ex",
   "The pattern can never match the type \n  {:terminal,\n   %FavnOrchestrator.RunState{\n     :asset_ref => {atom(), atom()},\n     :deployment_id => nil | binary(),\n     :error => _,\n     :event_seq => pos_integer(),\n     :id => binary(),\n     :inserted_at =>\n       nil\n       | %DateTime{\n           :calendar => atom(),\n           :day => pos_integer(),\n           :hour => non_neg_integer(),\n           :microsecond => {non_neg_integer(), non_neg_integer()},\n           :minute => non_neg_integer(),\n           :month => pos_integer(),\n           :second => non_neg_integer(),\n           :std_offset => integer(),\n           :time_zone => binary(),\n           :utc_offset => integer(),\n           :year => integer(),\n           :zone_abbr => binary()\n         },\n     :lineage_depth => non_neg_integer(),\n     :manifest_content_hash => binary(),\n     :manifest_version_id => binary(),\n     :max_attempts => pos_integer(),\n     :metadata => map(),\n     :params => map(),\n     :parent_run_id => nil | binary(),\n     :plan =>\n       nil\n       | %Favn.Plan{\n           :dependencies => :all | :none,\n           :node_stages => [[{{atom(), atom()}, _}]],\n           :nodes => %{\n             {{atom(), atom()}, _} => %{\n               :action => :observe | :run,\n               :downstream => [{{atom(), atom()}, _}],\n               :execution_pool => atom(),\n               :node_key => {{atom(), atom()}, _},\n               :ref => {atom(), atom()},\n               :retry_policy => %Favn.Retry.Policy{\n                 :backoff => %Favn.Retry.Backoff{\n                   :initial_ms => non_neg_integer(),\n                   :jitter => float(),\n                   :max_ms => non_neg_integer(),\n                   :strategy => :exponential | :fixed\n                 },\n                 :max_attempts => pos_integer()\n               },\n               :retry_policy_source => :asset | :default | :operator | :pipeline,\n               :stage => non_neg_integer(),\n               :upstream => [{{atom(), atom()}, _}],\n               :window =>\n                 nil\n                 | %Favn.Window.Runtime{\n                     :anchor_key => %{\n                       :kind => :day | :hour | :month | :year,\n                       :start_at_us => integer(),\n                       :timezone => binary()\n                     },\n                     :end_at => %DateTime{\n                       :calendar => atom(),\n                       :day => pos_integer(),\n                       :hour => non_neg_integer(),\n                       :microsecond => {non_neg_integer(), non_neg_integer()},\n                       :minute => non_neg_integer(),\n                       :month => pos_integer(),\n                       :second => non_neg_integer(),\n                       :std_offset => integer(),\n                       :time_zone => binary(),\n                       :utc_offset => integer(),\n                       :year => integer(),\n                       :zone_abbr => binary()\n                     },\n                     :key => %{\n                       :kind => :day | :hour | :month | :year,\n                       :start_at_us => integer(),\n                       :timezone => binary()\n                     },\n                     :kind => :day | :hour | :month | :year,\n                     :start_at => %DateTime{\n                       :calendar => atom(),\n                       :day => pos_integer(),\n                       :hour => non_neg_integer(),\n                       :microsecond => {non_neg_integer(), non_neg_integer()},\n                       :minute => non_neg_integer(),\n                       :month => pos_integer(),\n                       :second => non_neg_integer(),\n                       :std_offset => integer(),\n                       :time_zone => binary(),\n                       :utc_offset => integer(),\n                       :year => integer(),\n                       :zone_abbr => binary()\n                     },\n                     :timezone => binary()\n                   }\n             }\n           },\n           :stages => [Keyword.t(atom())],\n           :target_node_keys => [{{atom(), atom()}, _}],\n           :target_refs => Keyword.t(atom()),\n           :topo_order => Keyword.t(atom())\n         },\n     :plan_hash => binary(),\n     :required_runner_release_id => nil | binary(),\n     :rerun_of_run_id => nil | binary(),\n     :result => nil | map(),\n     :retry_backoff_ms => non_neg_integer(),\n     :root_run_id => nil | binary(),\n     :runner_execution_id => nil | binary(),\n     :snapshot_hash => binary(),\n     :status => :cancelled | :error | :ok | :partial | :pending | :running | :timed_out,\n     :storage_fencing_token => nil | pos_integer(),\n     :storage_owner_id => nil | binary(),\n     :submit_kind => :backfill_asset | :backfill_pipeline | :manual | :pipeline | :rerun,\n     :target_refs => Keyword.t(atom()),\n     :timeout_ms => pos_integer(),\n     :trigger => map(),\n     :updated_at =>\n       nil\n       | %DateTime{\n           :calendar => atom(),\n           :day => pos_integer(),\n           :hour => non_neg_integer(),\n           :microsecond => {non_neg_integer(), non_neg_integer()},\n           :minute => non_neg_integer(),\n           :month => pos_integer(),\n           :second => non_neg_integer(),\n           :std_offset => integer(),\n           :time_zone => binary(),\n           :utc_offset => integer(),\n           :year => integer(),\n           :zone_abbr => binary()\n         },\n     :workspace_id => nil | binary()\n   }}\n."},
  {"lib/favn_orchestrator/run_server.ex",
   "The pattern pattern \#{'__struct__':='Elixir.FavnOrchestrator.RunState'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_server/execution.ex", "The function call initialize will not succeed."},
  {"lib/favn_orchestrator/run_server/execution.ex", "The function call new will not succeed."},
  {"lib/favn_orchestrator/run_server/execution.ex",
   "The pattern pattern \#{'__struct__':='Elixir.FavnOrchestrator.RunState'} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_server/execution.ex",
   "The pattern can never match the type \n  {:cont,\n   %FavnOrchestrator.RunServer.Execution.RunExecutionState{\n     :accumulated_results => [any()],\n     :admission_timers => map(),\n     :admission_waiters => map(),\n     :await_monitors => map(),\n     :await_timers => map(),\n     :awaits => map(),\n     :freshness_context => nil | map(),\n     :manifest_index => map(),\n     :manifest_lease_id => nil | binary(),\n     :mode => :pipeline | :sequential,\n     :pipeline_continuation => nil | map(),\n     :retry_timers => map(),\n     :run => map(),\n     :runner_client => atom(),\n     :runner_opts => [any()],\n     :sequential_index => non_neg_integer(),\n     :sequential_refs => [any()],\n     :stage_admission_deadline_ms => nil | integer(),\n     :stage_attempt => pos_integer(),\n     :stage_decisions => map(),\n     :stage_freshness_context => nil | map(),\n     :stage_groups => [any()],\n     :stage_index => non_neg_integer(),\n     :stage_state => nil | map(),\n     :status => :retry_wait,\n     :terminal_failure => nil | map(),\n     :version => map(),\n     :work_set => map()\n   }}\n  | {:terminal,\n     %FavnOrchestrator.RunState{\n       :asset_ref => {_, _},\n       :deployment_id => nil | binary(),\n       :error => _,\n       :event_seq => pos_integer(),\n       :id => binary(),\n       :inserted_at => nil | map(),\n       :lineage_depth => non_neg_integer(),\n       :manifest_content_hash => binary(),\n       :manifest_version_id => binary(),\n       :max_attempts => pos_integer(),\n       :metadata => map(),\n       :params => map(),\n       :parent_run_id => nil | binary(),\n       :plan => nil | map(),\n       :plan_hash => binary(),\n       :required_runner_release_id => nil | binary(),\n       :rerun_of_run_id => nil | binary(),\n       :result => nil | map(),\n       :retry_backoff_ms => non_neg_integer(),\n       :root_run_id => nil | binary(),\n       :runner_execution_id => nil | binary(),\n       :snapshot_hash => nil | binary(),\n       :status => :cancelled | :error | :ok | :partial | :pending | :running | :timed_out,\n       :storage_fencing_token => nil | pos_integer(),\n       :storage_owner_id => nil | binary(),\n       :submit_kind => :backfill_asset | :backfill_pipeline | :manual | :pipeline | :rerun,\n       :target_refs => [any()],\n       :timeout_ms => pos_integer(),\n       :trigger => map(),\n       :updated_at => nil | map(),\n       :workspace_id => nil | binary()\n     }}\n  | {:persist_retry,\n     %FavnOrchestrator.RunServer.Execution.RunExecutionState{\n       :accumulated_results => [any()],\n       :admission_timers => map(),\n       :admission_waiters => map(),\n       :await_monitors => map(),\n       :await_timers => map(),\n       :awaits => map(),\n       :freshness_context => nil | map(),\n       :manifest_index => map(),\n       :manifest_lease_id => nil | binary(),\n       :mode => :pipeline | :sequential,\n       :pipeline_continuation => nil | map(),\n       :retry_timers => map(),\n       :run => map(),\n       :runner_client => atom(),\n       :runner_opts => [any()],\n       :sequential_index => non_neg_integer(),\n       :sequential_refs => [any()],\n       :stage_admission_deadline_ms => nil | integer(),\n       :stage_attempt => pos_integer(),\n       :stage_decisions => map(),\n       :stage_freshness_context => nil | map(),\n       :stage_groups => [any()],\n       :stage_index => non_neg_integer(),\n       :stage_state => nil | map(),\n       :status =>\n         :admission_wait | :awaiting | :classifying | :retry_wait | :starting | :submitting,\n       :terminal_failure => nil | map(),\n       :version => map(),\n       :work_set => map()\n     },\n     %FavnOrchestrator.RunServer.PersistenceRetry{\n       :data => map(),\n       :event_type => atom(),\n       :resume => _,\n       :run => map()\n     }, _}\n."},
  {"lib/favn_orchestrator/run_server/execution.ex",
   "The pattern can never match the type \n  {:persist_retry,\n   %FavnOrchestrator.RunServer.PersistenceRetry{\n     :data => map(),\n     :event_type => atom(),\n     :resume => _,\n     :run => %FavnOrchestrator.RunState{\n       :asset_ref => {_, _},\n       :deployment_id => nil | binary(),\n       :error => _,\n       :event_seq => pos_integer(),\n       :id => binary(),\n       :inserted_at => nil | map(),\n       :lineage_depth => non_neg_integer(),\n       :manifest_content_hash => binary(),\n       :manifest_version_id => binary(),\n       :max_attempts => pos_integer(),\n       :metadata => map(),\n       :params => map(),\n       :parent_run_id => nil | binary(),\n       :plan => nil | map(),\n       :plan_hash => binary(),\n       :required_runner_release_id => nil | binary(),\n       :rerun_of_run_id => nil | binary(),\n       :result => nil | map(),\n       :retry_backoff_ms => non_neg_integer(),\n       :root_run_id => nil | binary(),\n       :runner_execution_id => nil | binary(),\n       :snapshot_hash => nil | binary(),\n       :status => :cancelled | :error | :ok | :partial | :pending | :running | :timed_out,\n       :storage_fencing_token => nil | pos_integer(),\n       :storage_owner_id => nil | binary(),\n       :submit_kind => :backfill_asset | :backfill_pipeline | :manual | :pipeline | :rerun,\n       :target_refs => [any()],\n       :timeout_ms => pos_integer(),\n       :trigger => map(),\n       :updated_at => nil | map(),\n       :workspace_id => nil | binary()\n     }\n   }, _}\n."},
  {"lib/favn_orchestrator/run_server/execution.ex",
   "The pattern can never match the type \n  {:persist_retry,\n   %FavnOrchestrator.RunServer.PersistenceRetry{\n     :data => map(),\n     :event_type => atom(),\n     :resume => _,\n     :run => %FavnOrchestrator.RunState{\n       :asset_ref => {_, _},\n       :deployment_id => nil | binary(),\n       :error => _,\n       :event_seq => pos_integer(),\n       :id => binary(),\n       :inserted_at => nil | map(),\n       :lineage_depth => non_neg_integer(),\n       :manifest_content_hash => binary(),\n       :manifest_version_id => binary(),\n       :max_attempts => pos_integer(),\n       :metadata => map(),\n       :params => map(),\n       :parent_run_id => nil | binary(),\n       :plan => nil | map(),\n       :plan_hash => binary(),\n       :required_runner_release_id => nil | binary(),\n       :rerun_of_run_id => nil | binary(),\n       :result => nil | map(),\n       :retry_backoff_ms => non_neg_integer(),\n       :root_run_id => nil | binary(),\n       :runner_execution_id => nil | binary(),\n       :snapshot_hash => nil | binary(),\n       :status => :cancelled | :error | :ok | :partial | :pending | :running | :timed_out,\n       :storage_fencing_token => nil | pos_integer(),\n       :storage_owner_id => nil | binary(),\n       :submit_kind => :backfill_asset | :backfill_pipeline | :manual | :pipeline | :rerun,\n       :target_refs => [any()],\n       :timeout_ms => pos_integer(),\n       :trigger => map(),\n       :updated_at => nil | map(),\n       :workspace_id => nil | binary()\n     }\n   }, _}\n  | {:error,\n     %FavnOrchestrator.RunState{\n       :asset_ref => {atom(), atom()},\n       :deployment_id => nil | binary(),\n       :error => _,\n       :event_seq => pos_integer(),\n       :id => binary(),\n       :inserted_at =>\n         nil\n         | %DateTime{\n             :calendar => atom(),\n             :day => pos_integer(),\n             :hour => non_neg_integer(),\n             :microsecond => {_, _},\n             :minute => non_neg_integer(),\n             :month => pos_integer(),\n             :second => non_neg_integer(),\n             :std_offset => integer(),\n             :time_zone => binary(),\n             :utc_offset => integer(),\n             :year => integer(),\n             :zone_abbr => binary()\n           },\n       :lineage_depth => non_neg_integer(),\n       :manifest_content_hash => binary(),\n       :manifest_version_id => binary(),\n       :max_attempts => pos_integer(),\n       :metadata => map(),\n       :params => map(),\n       :parent_run_id => nil | binary(),\n       :plan =>\n         nil\n         | %Favn.Plan{\n             :dependencies => :all | :none,\n             :node_stages => [any()],\n             :nodes => map(),\n             :stages => [any()],\n             :target_node_keys => [any()],\n             :target_refs => [any()],\n             :topo_order => [any()]\n           },\n       :plan_hash => binary(),\n       :required_runner_release_id => nil | binary(),\n       :rerun_of_run_id => nil | binary(),\n       :result => nil | map(),\n       :retry_backoff_ms => non_neg_integer(),\n       :root_run_id => nil | binary(),\n       :runner_execution_id => nil | binary(),\n       :snapshot_hash => nil | binary(),\n       :status => :cancelled | :error | :ok | :partial | :pending | :running | :timed_out,\n       :storage_fencing_token => nil | pos_integer(),\n       :storage_owner_id => nil | binary(),\n       :submit_kind => :backfill_asset | :backfill_pipeline | :manual | :pipeline | :rerun,\n       :target_refs => [{_, _}],\n       :timeout_ms => pos_integer(),\n       :trigger => map(),\n       :updated_at =>\n         nil\n         | %DateTime{\n             :calendar => atom(),\n             :day => pos_integer(),\n             :hour => non_neg_integer(),\n             :microsecond => {_, _},\n             :minute => non_neg_integer(),\n             :month => pos_integer(),\n             :second => non_neg_integer(),\n             :std_offset => integer(),\n             :time_zone => binary(),\n             :utc_offset => integer(),\n             :year => integer(),\n             :zone_abbr => binary()\n           },\n       :workspace_id => nil | binary()\n     }, [], [{{_, _}, _}]}\n."},
  {"lib/favn_orchestrator/run_server/execution.ex", "Function restore_retry_wait/1 will never be called."},
  {"lib/favn_orchestrator/run_server/execution.ex", "Function restore_retry_position/3 will never be called."},
  {"lib/favn_orchestrator/run_server/execution.ex", "Function load_pipeline_retry/2 will never be called."},
  {"lib/favn_orchestrator/run_server/execution.ex", "Function persisted_node_results/1 will never be called."},
  {"lib/favn_orchestrator/run_server/execution.ex", "Function metadata_field/2 will never be called."},
  {"lib/favn_orchestrator/run_server/execution.ex", "Function pipeline_stage_groups/1 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "The test %FavnOrchestrator.Persistence.Error{\n  :details => map(),\n  :kind =>\n    :conflict\n    | :constraint\n    | :fenced\n    | :forbidden\n    | :internal\n    | :invalid\n    | :limit_exceeded\n    | :not_found\n    | :timeout\n    | :unavailable\n    | :unsupported,\n  :message => binary(),\n  :retryable? => boolean()\n} == :external_cancel can never evaluate to 'true'."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "Function start_submitted_attempt/5 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex", "Function sequential_entry/5 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex", "The pattern can never match the type :terminal."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex", "Function schedule_retry/2 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex", "Function attempt_start_event/1 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "Function persist_submitted_ownership_snapshot/1 has no local return."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "The function call externally_cancelled? will not succeed."},
  {"lib/favn_orchestrator/run_server/execution/sequential.ex",
   "The pattern pattern <\#{'__struct__':='Elixir.FavnOrchestrator.RunState'}, __execution_id@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "The pattern variable __ctx@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "The pattern can never match the type \n  %{\n    :attempt => _,\n    :batch_count => pos_integer(),\n    :batch_started_ms => integer(),\n    :current_run => %FavnOrchestrator.RunState{},\n    :decisions => map(),\n    :entries_rev => [],\n    :freshness_context => map(),\n    :lease => nil | map(),\n    :manifest_index => %Favn.Manifest.Index{},\n    :manifest_lease_id => _,\n    :materialization_claim => map(),\n    :node_key => {{_, _}, _},\n    :node_keys => nonempty_maybe_improper_list(),\n    :queued_steps => %MapSet{},\n    :resource_circuit_permits => [map()],\n    :rest => _,\n    :runner_client => _,\n    :runner_opts => _,\n    :stage => _,\n    :terminal_failure => nil | map(),\n    :version => %Favn.Manifest.Version{},\n    :waiters => [],\n    :work => %Favn.Contracts.RunnerWork{\n      :asset_ref => nil | {_, _},\n      :asset_refs => [any()],\n      :asset_step_id => nil | binary(),\n      :attempt => pos_integer(),\n      :deadline_at => nil | map(),\n      :execution_id => binary(),\n      :execution_package => nil | map(),\n      :manifest_content_hash => binary(),\n      :manifest_lease_id => nil | binary(),\n      :manifest_version_id => binary(),\n      :max_attempts => pos_integer(),\n      :metadata => map(),\n      :node_identity => nil | map(),\n      :params => map(),\n      :pipeline => nil | map(),\n      :planned_asset_refs => [any()],\n      :required_runner_release_id => binary(),\n      :run_id => nil | binary(),\n      :run_started_at => nil | map(),\n      :runtime_input_pin => nil | map(),\n      :stage => non_neg_integer(),\n      :trigger => map()\n    }\n  },\n  nil | {_, _},\n  _,\n  %FavnOrchestrator.Persistence.Error{\n    :details => map(),\n    :kind =>\n      :conflict\n      | :constraint\n      | :fenced\n      | :forbidden\n      | :internal\n      | :invalid\n      | :limit_exceeded\n      | :not_found\n      | :timeout\n      | :unavailable\n      | :unsupported,\n    :message => binary(),\n    :retryable? => boolean()\n  }\n."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function submit_started_entry/3 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function submit_started_entry_after_ownership/5 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function persist_submitted_ownership_snapshot/1 has no local return."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "The function call externally_cancelled? will not succeed."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function with_inflight_execution/3 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function inflight_ids_from_metadata/1 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function attempt_start_event/1 will never be called."},
  {"lib/favn_orchestrator/run_server/execution/stage_admission.ex",
   "Function decision_freshness_key/2 will never be called."},
  {"lib/favn_orchestrator/runner_client/beam_node.ex", "Function cancel_work/1 has no local return."},
  {"lib/favn_orchestrator/runner_client/beam_node.ex", "The function call cancel_work will not succeed."},
  {"lib/favn_orchestrator/runs.ex", "The function call bounded_command_id will not succeed."},
  {"lib/favn_orchestrator/scheduler/persistence_runtime.ex",
   "The pattern variable __run@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/freshness/asset_freshness_state_codec.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/storage/freshness/asset_freshness_state_codec.ex",
   "The pattern variable _input_versions@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/materialization_claim_codec.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/storage/run_query.ex",
   "The pattern pattern <__value@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/run_snapshot_codec.ex",
   "The pattern variable _metadata@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/storage/run_snapshot_codec.ex",
   "The pattern variable _result@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_orchestrator/transition_writer.ex",
   "The pattern pattern <\#{'__struct__':='Elixir.FavnOrchestrator.RunEvent'}, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_runner.ex",
   "The pattern variable __error@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_runner.ex", "Function cancel_work/1 has no local return."},
  {"lib/favn_runner.ex", "The function call cancel_work will not succeed."},
  {"lib/favn_runner/execution_lifecycle.ex",
   "The @spec for new has an opaque subtype which is violated by the success typing."},
  {"lib/favn_runner/manifest_resolver.ex",
   "The pattern pattern <_asset_ref@1, __asset_refs@1> can never match the type, because it is covered by previous clauses."},
  {"lib/favn_runner/manifest_store.ex",
   "The pattern variable __assets@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_runner/server.ex", "Function cancel_work/1 has no local return."},
  {"lib/favn_runner/server.ex", "The function call cancel_work will not succeed."},
  {"lib/favn_storage_postgres/backfills/store.ex", "The pattern can never match the type true."},
  {"lib/favn_storage_postgres/registry/store.ex",
   "The pattern can never match the type \n  %{\n    :asset_count => _,\n    :content_hash => _,\n    :pipeline_count => _,\n    :required_runner_release_id => _,\n    :runner_contract_version => _,\n    :schedule_count => _,\n    :schema_version => _\n  },\n  :asset_count\n  | :content_hash\n  | :pipeline_count\n  | :required_runner_release_id\n  | :runner_contract_version\n  | :schedule_count\n  | :schema_version\n."},
  {"lib/favn_storage_postgres/runs/decoder.ex", "Unknown type: FavnStoragePostgres.Schemas.Run.t/0."},
  {"lib/favn_storage_postgres/runs/decoder.ex",
   "The pattern can never match the type \n  {:error,\n   %FavnOrchestrator.Persistence.Error{\n     :details => map(),\n     :kind =>\n       :conflict\n       | :constraint\n       | :fenced\n       | :forbidden\n       | :internal\n       | :invalid\n       | :limit_exceeded\n       | :not_found\n       | :timeout\n       | :unavailable\n       | :unsupported,\n     :message => binary(),\n     :retryable? => boolean()\n   }}\n."},
  {"lib/favn_storage_postgres/runs/decoder.ex", "The function call decode_run will not succeed."},
  {"lib/favn_storage_postgres/runs/store.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/favn_storage_postgres/runs/store.ex",
   "The pattern can never match the type \n  {:error,\n   %FavnOrchestrator.Persistence.Error{\n     :details => map(),\n     :kind =>\n       :conflict\n       | :constraint\n       | :fenced\n       | :forbidden\n       | :internal\n       | :invalid\n       | :limit_exceeded\n       | :not_found\n       | :timeout\n       | :unavailable\n       | :unsupported,\n     :message => binary(),\n     :retryable? => boolean()\n   }}\n."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/asset_detail_live.ex", "The pattern can never match the type {:error, :backend_unavailable}."},
  {"lib/favn_view/asset_detail_live.ex", "Function asset_from_detail/2 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function run_context_path/2 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function window_range/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function asset_name/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function status_label/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function status_tone/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function window_kind_label/1 will never be called."},
  {"lib/favn_view/asset_detail_live.ex", "Function missing_freshness_detail/0 will never be called."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/asset_detail_live.ex", "The pattern can never match the type :invalid_context | :unauthenticated."},
  {"lib/favn_view/asset_run_logs_live.ex", "The guard clause can never succeed."},
  {"lib/favn_view/auth.ex", "The pattern can never match the type {:error, :invalid_session | :missing_session}."},
  {"lib/favn_view/auth.ex", "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_view/auth/scope.ex", "The function call get will not succeed."},
  {"lib/favn_view/components/run_detail_page/samples.ex",
   "The test :error | :ok | :queued | :running | :skipped_fresh =:= :pending can never evaluate to 'true'."},
  {"lib/favn_view/controllers/operator_session_controller.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_view/logs_live_support.ex", "Function target_label/1 will never be called."},
  {"lib/favn_view/logs_live_support.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/logs_live_support.ex", "Function run_context_from_public/2 will never be called."},
  {"lib/favn_view/logs_live_support.ex", "Function asset_context_from_public/1 will never be called."},
  {"lib/favn_view/logs_live_support.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function normalize_window_kind/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/pipeline_detail_live.ex", "The pattern can never match the type {:error, :backend_unavailable}."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function pipeline_from_detail/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "The pattern can never match the type nil."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_kind/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_timezone/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function pipeline_name/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function dependencies_label/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_label/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function window_label/2 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function status_label/1 will never be called."},
  {"lib/favn_view/pipeline_detail_live.ex", "Function last_run_label/1 will never be called."},
  {"lib/favn_view/plugs/trusted_proxy_headers.ex",
   "The pattern variable __unknown_peer@1 can never match the type, because it is covered by previous clauses."},
  {"lib/favn_view/run_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/run_detail_live.ex", "Function retry_remaining_submitted_label/2 will never be called."},
  {"lib/favn_view/run_detail_live.ex", "Function retry_remaining_partial_label/2 will never be called."},
  {"lib/favn_view/run_detail_live.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/runs_list_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/runs_list_live.ex", "Function detail_from_public/1 will never be called."},
  {"lib/favn_view/runs_list_live.ex", "Function child_run_from_public/2 will never be called."},
  {"lib/favn_view/runs_list_live.ex", "Function display_run_status/1 will never be called."},
  {"lib/favn_view/runs_list_live.ex", "Function progress_label/2 will never be called."},
  {"lib/favn_view/runs_list_live.ex", "Function progress_title/1 will never be called."},
  {"lib/favn_view/storybook.ex",
   "Callback info about the PhoenixStorybook.BackendBehaviour behaviour is not available."},
  {"lib/favn_view/storybook.ex", "Function PhoenixStorybook.Entries.story_file_suffix/0 does not exist."},
  {"lib/mix/tasks/favn.postgres.maintenance.ex", "Function usage!/0 has no local return."},
  {"lib/mix/tasks/favn.postgres.provision_workspace.ex", "Function usage!/0 has no local return."},
  {"storybook/components/app_shell.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/app_shell.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/app_shell.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/app_shell.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/app_shell.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/asset_catalogue_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/asset_catalogue_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/asset_catalogue_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/asset_catalogue_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/asset_catalogue_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/asset_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/asset_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/asset_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/asset_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/asset_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/glass_panel.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/glass_panel.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/glass_panel.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/glass_panel.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/glass_panel.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/icon.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/icon.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/icon.story.exs", "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/icon.story.exs", "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/icon.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/icon.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/icon_nav.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/icon_nav.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/icon_nav.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/icon_nav.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/icon_nav.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/lineage_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/lineage_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/lineage_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/lineage_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/lineage_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/log_viewer.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/log_viewer.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/log_viewer.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/log_viewer.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/log_viewer.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/log_viewer.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/mobile_icon_nav.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/mobile_icon_nav.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/mobile_icon_nav.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/mobile_icon_nav.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/mobile_icon_nav.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/mode_rail.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/mode_rail.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/mode_rail.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/mode_rail.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/mode_rail.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/output_metadata.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/output_metadata.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/output_metadata.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/output_metadata.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/output_metadata.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/output_metadata.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/pipeline_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/pipeline_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/pipeline_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/pipeline_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/pipeline_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/pipeline_detail_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/pipelines_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/pipelines_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/pipelines_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/pipelines_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/pipelines_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/run_detail_events_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/run_detail_events_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/run_detail_events_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/run_detail_events_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/run_detail_events_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/run_detail_events_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/run_detail_failures_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/run_detail_failures_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/run_detail_failures_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/run_detail_failures_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/run_detail_failures_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/run_detail_failures_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/run_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/run_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/run_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/run_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/run_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/run_detail_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/run_detail_timeline_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/run_detail_timeline_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/run_detail_timeline_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/run_detail_timeline_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/run_detail_timeline_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/run_detail_timeline_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/run_detail_window_runs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/run_detail_window_runs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/run_detail_window_runs_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/run_detail_window_runs_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/run_detail_window_runs_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/run_detail_window_runs_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/components/runs_list_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/runs_list_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/runs_list_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/runs_list_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/runs_list_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/schedule_activation_badge.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/schedule_activation_badge.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/schedule_activation_badge.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/schedule_activation_badge.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/schedule_activation_badge.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/schedule_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/schedule_detail_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/schedule_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/schedule_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/schedule_detail_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/schedule_occurrence_preview_table.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/schedule_occurrence_preview_table.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/schedule_occurrence_preview_table.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/schedule_occurrence_preview_table.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/schedule_occurrence_preview_table.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/schedule_runtime_badge.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/schedule_runtime_badge.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/schedule_runtime_badge.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/schedule_runtime_badge.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/schedule_runtime_badge.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/schedule_scheduler_error_badge.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/schedule_scheduler_error_badge.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/schedule_scheduler_error_badge.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/schedule_scheduler_error_badge.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/schedule_scheduler_error_badge.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/schedules_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/schedules_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/schedules_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/schedules_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/schedules_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/selected_window_actions.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/selected_window_actions.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/selected_window_actions.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/selected_window_actions.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/selected_window_actions.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/selected_window_actions.story.exs", "The pattern can never match the type :error."},
  {"storybook/components/selected_window_actions.story.exs", "The pattern can never match the type :error | :success."},
  {"storybook/components/theme_toggle.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/theme_toggle.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/theme_toggle.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/theme_toggle.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/theme_toggle.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/timeline_window.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/timeline_window.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/timeline_window.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/timeline_window.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/timeline_window.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/components/window_timeline_panel.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/components/window_timeline_panel.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/components/window_timeline_panel.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/components/window_timeline_panel.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/components/window_timeline_panel.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/pages/asset_run_logs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/pages/asset_run_logs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/pages/asset_run_logs_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/pages/asset_run_logs_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/pages/asset_run_logs_page.story.exs",
   "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/pages/asset_run_logs_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/pages/logs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/pages/logs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/pages/logs_page.story.exs", "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/pages/logs_page.story.exs", "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/pages/logs_page.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/pages/logs_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"storybook/pages/run_logs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.ComponentBehaviour behaviour is not available."},
  {"storybook/pages/run_logs_page.story.exs",
   "Callback info about the PhoenixStorybook.Story.StoryBehaviour behaviour is not available."},
  {"storybook/pages/run_logs_page.story.exs",
   "Function PhoenixStorybook.Stories.Doc.fetch_doc_as_html/2 does not exist."},
  {"storybook/pages/run_logs_page.story.exs",
   "Function PhoenixStorybook.Stories.Attr.merge_attributes/2 does not exist."},
  {"storybook/pages/run_logs_page.story.exs", "Function PhoenixStorybook.Stories.Slot.merge_slots/2 does not exist."},
  {"storybook/pages/run_logs_page.story.exs",
   "Function PhoenixStorybook.TemplateHelpers.default_template/0 does not exist."},
  {"test/support/conn_case.ex", "Function ExUnit.Callbacks.__merge__/4 does not exist."},
  {"test/support/conn_case.ex", "Function ExUnit.Callbacks.__noop__/0 does not exist."},
  {"test/support/conn_case.ex", "Function ExUnit.CaseTemplate.__proxy__/2 does not exist."}
]
