# Historical warning baseline generated with the CI-pinned Elixir/OTP toolchain.
# Remove entries when debt is fixed; do not regenerate this file to accept new warnings.
[
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator.ex",
   "The pattern can never match the type {:error, :forbidden | :unauthenticated}."},
  {"lib/favn_orchestrator.ex", "Function operator_backfill_opts/3 will never be called."},
  {"lib/favn_orchestrator.ex", "Function operator_refresh/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function execution_group_status/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function merge_coverage_metadata/2 will never be called."},
  {"lib/favn_orchestrator.ex",
   "Function remaining_retry_plan_fingerprint/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function begin_operator_command/8 will never be called."},
  {"lib/favn_orchestrator.ex", "Function idempotency_key_opts/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function put_rebuild_plan_idempotency/2 will never be called."},
  {"lib/favn_orchestrator.ex",
   "Function put_rebuild_command_idempotency/2 will never be called."},
  {"lib/favn_orchestrator.ex", "Function run_command_opts/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function finish_operator_result/8 will never be called."},
  {"lib/favn_orchestrator.ex", "Function finish_operator_audit/9 will never be called."},
  {"lib/favn_orchestrator.ex", "Function operator_error_code/1 will never be called."},
  {"lib/favn_orchestrator.ex", "Function admin?/1 will never be called."},
  {"lib/favn_orchestrator/api/actors_router.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_credentials | :unauthenticated}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_session | :unauthenticated}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type \n  {:error,\n   :service_unauthorized | :unauthenticated | {:missing_field, <<_::64, _::size(40)>>}}\n."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :service_unauthorized | :unauthenticated | {:missing_field, <<_::104>>}}."},
  {"lib/favn_orchestrator/api/auth_router.ex", "Function audit/5 will never be called."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/api/auth_router.ex",
   "Function persistence_roles/1 will never be called."},
  {"lib/favn_orchestrator/api/coverage_router.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_orchestrator/api/coverage_router.ex",
   "Function audit_submit/8 will never be called."},
  {"lib/favn_orchestrator/api/runs_router.ex", "The guard clause can never succeed."},
  {"lib/favn_orchestrator/api/runs_router.ex", "The pattern can never match the type true."},
  {"lib/favn_orchestrator/auth.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_orchestrator/auth.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_orchestrator/auth.ex",
   "The pattern can never match the type {:error, :invalid_session}."},
  {"lib/favn_orchestrator/auth/store.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type {:error, :backend_unavailable}."},
  {"lib/favn_view/asset_detail_live.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/asset_detail_live.ex", "The pattern can never match the type {:error, _}."},
  {"lib/favn_view/controllers/operator_session_controller.ex",
   "The pattern can never match the type {:error, :invalid_credentials}."},
  {"lib/favn_view/logs_live_support.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/logs_live_support.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/pipeline_detail_live.ex",
   "The pattern can never match the type {:error, :backend_unavailable}."},
  {"lib/favn_view/pipeline_detail_live.ex", "The pattern can never match the type nil."},
  {"lib/favn_view/run_detail_live.ex",
   "The pattern can never match the type {:error, :forbidden | :invalid_context | :unauthenticated}."},
  {"lib/favn_view/run_detail_live.ex",
   "The pattern can never match the type :forbidden | :invalid_context | :unauthenticated."}
]
