defmodule FavnView.Endpoint do
  use Phoenix.Endpoint, otp_app: :favn_view

  # The session is cookie-backed. It intentionally stores only a random browser
  # session id and LiveView socket topic; the raw orchestrator token stays
  # server-side. Cookies are HTTP-only and encrypted, and production config must
  # set `secure: true`.
  @session_options Application.compile_env!(:favn_view, :session_cookie_options)
  @trusted_proxy_force_ssl Application.compile_env(
                             :favn_view,
                             :trusted_proxy_force_ssl,
                             false
                           )

  @doc false
  def session_options, do: @session_options

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :favn_view,
    gzip: not code_reloading?,
    only: FavnView.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  if @trusted_proxy_force_ssl do
    plug FavnView.Plugs.TrustedProxyHeaders
    plug Plug.SSL, host: nil, hsts: true
  end

  plug FavnView.Plugs.RequestParsers

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FavnView.Router
end
