defmodule FavnView.Endpoint do
  use Phoenix.Endpoint, otp_app: :favn_view

  @doc false
  def session_options, do: FavnView.ProductionRuntimeConfig.session_cookie_options()

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :favn_view,
    gzip: not code_reloading?,
    only: FavnView.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug FavnView.Plugs.RuntimeTransportSecurity

  plug FavnView.Plugs.RequestParsers

  plug Plug.MethodOverride
  plug Plug.Head
  plug FavnView.Plugs.RuntimeSession
  plug FavnView.Router
end
