import Config

# Maintainer-only source runtime used by Phoenix/Tidewave. The supported
# customer development topology is generated by `mix favn.dev` and runs in
# Docker Compose. Keep these reads out of shared/production configuration while
# still allowing an umbrella-root source server to compose PostgreSQL explicitly.
database_url = System.get_env("FAVN_DATABASE_URL")
runtime_input_pin_key = System.get_env("FAVN_RUNTIME_INPUT_PIN_KEY")

if is_binary(database_url) and database_url != "" and is_binary(runtime_input_pin_key) and
     runtime_input_pin_key != "" do
  config :favn_orchestrator,
    local_dev_mode: true,
    workspace_ids: ["local-dev"],
    persistence_options: [
      url: database_url,
      ssl_mode: :disable,
      pool_size: 10,
      instance_id: "source-dev"
    ]

  config :favn_storage_postgres,
    runtime_input_pin_keys: %{1 => runtime_input_pin_key},
    runtime_input_pin_current_key_version: 1
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :favn_view, FavnView.Endpoint,
  http: [
    ip: {127, 0, 0, 1},
    port: System.get_env("FAVN_VIEW_PORT", System.get_env("PORT", "4173")) |> String.to_integer()
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Us78fGI34yxUbXGH5KjKVxK6KhSoad+Zy01o8KwaT1etO8OTjhQSr7Zxd5+X2693",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:favn_view, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:favn_view, ~w(--watch)]}
  ],
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/favn_view/router\.ex$"E,
      ~r"lib/favn_view/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard.
config :favn_view, dev_routes: true

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true
