import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :favn_view, FavnView.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :favn_view, trusted_proxy_force_ssl: true

config :favn_view,
  require_secure_cookies: true,
  session_cookie_options: [
    store: :cookie,
    key: "_favn_view_key",
    signing_salt: "zqy+dPTK",
    encryption_salt: "favn-view-session-v1",
    same_site: "Lax",
    http_only: true,
    secure: true
  ]
