#!/bin/sh
set -eu

: "${FAVN_RUNTIME_DATABASE_PASSWORD:?FAVN_RUNTIME_DATABASE_PASSWORD is required}"

psql \
  --set ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  --set runtime_password="$FAVN_RUNTIME_DATABASE_PASSWORD" <<'SQL'
CREATE ROLE favn_runtime
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  PASSWORD :'runtime_password';

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE favn FROM PUBLIC;
GRANT CONNECT ON DATABASE favn TO favn_runtime;
SQL
