defmodule Favn.SQL.Contract do
  @moduledoc """
  Typed, manifest-visible output contract for one SQL asset.

  Contracts preserve ordered logical columns, explicit fragment-composition
  provenance, optional structured or descriptive grain, explicit unique keys,
  an optional bounded row-count claim, and authored column lineage. They are
  assertions about output, not SQL query generators.

  The contract compiler exposes at most three grouped generated check
  specifications for required columns, keys, and row count. The SQL asset
  frontend compiles those specifications into ordinary `Favn.SQL.Check` values,
  so wide contracts remain bounded while contract and custom checks share one
  transaction, one policy vocabulary, and one durable result model.
  """

  alias Favn.SQL.{Check, Template}
  alias Favn.SQL.Contract.{Column, Composition, Grain, Param, RowCount, UniqueKey}

  @max_columns 1_000
  @max_compositions 128
  @max_unique_keys 128

  @enforce_keys [:columns]
  defstruct [:grain, :row_count, columns: [], compositions: [], unique_keys: []]

  @type t :: %__MODULE__{
          grain: Grain.t() | nil,
          columns: [Column.t()],
          compositions: [Composition.t()],
          unique_keys: [UniqueKey.t()],
          row_count: RowCount.t() | nil
        }

  @type check_spec :: %{
          required(:name) => atom(),
          required(:claim_id) => String.t(),
          required(:at) => Favn.SQL.Check.phase(),
          required(:on_violation) => Favn.SQL.Check.violation_policy(),
          required(:when) => Favn.SQL.Check.condition(),
          required(:message) => String.t(),
          required(:sql) => String.t()
        }

  @doc "Builds and validates a compiled contract."
  @spec new!(map() | keyword()) :: t()
  def new!(fields) when is_map(fields) or is_list(fields) do
    fields = Map.new(fields)

    %__MODULE__{
      grain: normalize_grain(Map.get(fields, :grain)),
      columns: Enum.map(Map.get(fields, :columns, []), &normalize_column/1),
      compositions: Enum.map(Map.get(fields, :compositions, []), &normalize_composition/1),
      unique_keys: Enum.map(Map.get(fields, :unique_keys, []), &normalize_unique_key/1),
      row_count: normalize_row_count(Map.get(fields, :row_count))
    }
    |> validate!()
  end

  @doc "Validates a compiled or rehydrated output contract."
  @spec validate!(t()) :: t()
  def validate!(%__MODULE__{} = contract) do
    unless is_list(contract.columns) and contract.columns != [],
      do: raise(ArgumentError, "SQL output contract requires at least one column")

    if length(contract.columns) > @max_columns,
      do: raise(ArgumentError, "SQL output contract supports at most #{@max_columns} columns")

    unless is_list(contract.compositions),
      do: raise(ArgumentError, "SQL output contract compositions must be a list")

    if length(contract.compositions) > @max_compositions,
      do:
        raise(
          ArgumentError,
          "SQL output contract supports at most #{@max_compositions} fragment compositions"
        )

    unless is_list(contract.unique_keys),
      do: raise(ArgumentError, "SQL output contract unique keys must be a list")

    if length(contract.unique_keys) > @max_unique_keys,
      do:
        raise(
          ArgumentError,
          "SQL output contract supports at most #{@max_unique_keys} unique keys"
        )

    Enum.each(contract.columns, &Column.validate!/1)
    Enum.each(contract.compositions, &Composition.validate!/1)
    if contract.grain, do: Grain.validate!(contract.grain)
    Enum.each(contract.unique_keys, &UniqueKey.validate!/1)
    if contract.row_count, do: RowCount.validate!(contract.row_count)

    names = Enum.map(contract.columns, & &1.name)
    ensure_unique_columns!(names)
    ensure_compositions!(contract.compositions, names)
    ensure_referenced_columns!(contract, MapSet.new(names))
    ensure_unique_keys!(contract.unique_keys)
    ensure_unique_renames!(contract.columns, MapSet.new(names))
    ensure_grain_nullability!(contract)
    contract
  end

  @doc "Returns deterministic data-check specifications generated by a contract."
  @spec generated_check_specs(t()) :: [check_spec()]
  def generated_check_specs(%__MODULE__{} = contract) do
    contract = validate!(contract)

    row_count_specs(contract) ++ non_null_specs(contract) ++ unique_specs(contract)
  end

  @doc "Validates that compiled checks contain exactly the claims generated by the contract."
  @spec validate_generated_checks!(t() | nil, [Check.t()]) :: [Check.t()]
  def validate_generated_checks!(contract, checks) when is_list(checks) do
    checks = Check.validate_list!(checks)
    actual = Enum.filter(checks, &(&1.origin == :contract))

    expected =
      case contract do
        nil -> []
        %__MODULE__{} = value -> generated_check_specs(value)
      end

    if Enum.map(actual, & &1.claim_id) != Enum.map(expected, & &1.claim_id) do
      raise ArgumentError, "SQL contract-generated checks do not match the contract claims"
    end

    Enum.zip(actual, expected)
    |> Enum.each(fn {check, spec} -> validate_generated_check!(check, spec) end)

    checks
  end

  @doc "Returns the maximum ordered columns accepted by one output contract."
  @spec max_columns() :: pos_integer()
  def max_columns, do: @max_columns

  @doc "Returns the maximum explicit fragment compositions accepted by one contract."
  @spec max_compositions() :: pos_integer()
  def max_compositions, do: @max_compositions

  @doc "Returns the maximum explicit unique keys accepted by one output contract."
  @spec max_unique_keys() :: pos_integer()
  def max_unique_keys, do: @max_unique_keys

  @doc "Returns typed runtime parameter requirements introduced by contract claims."
  @spec runtime_param_requirements(t() | nil) :: %{optional(atom()) => :non_neg_integer}
  def runtime_param_requirements(nil), do: %{}

  def runtime_param_requirements(%__MODULE__{
        row_count: %RowCount{equals: %Param{name: name}}
      }),
      do: %{name => :non_neg_integer}

  def runtime_param_requirements(%__MODULE__{}), do: %{}

  @doc "Returns whether an observed backend type satisfies a logical contract type."
  @spec compatible_type?(Column.logical_type(), String.t() | nil) :: boolean()
  def compatible_type?(logical_type, observed_type) do
    observed = normalize_observed_type(observed_type)

    logical_type == observed or
      (logical_type == :float and observed == :decimal)
  end

  @doc "Normalizes common backend SQL types into contract logical types."
  @spec normalize_observed_type(String.t() | nil) :: Column.logical_type() | :unknown
  def normalize_observed_type(nil), do: :unknown

  def normalize_observed_type(type) when is_binary(type) do
    normalized =
      type
      |> String.upcase()
      |> String.trim()

    if String.ends_with?(normalized, "]") do
      :unknown
    else
      normalize_scalar_observed_type(normalized)
    end
  end

  defp normalize_scalar_observed_type(type) do
    base =
      type
      |> String.replace(~r/\(.*/, "")

    cond do
      base in ["BOOLEAN", "BOOL", "LOGICAL"] ->
        :boolean

      Regex.match?(~r/^(U?TINYINT|U?SMALLINT|U?INTEGER|U?BIGINT|HUGEINT|INT\d*)$/, base) ->
        :integer

      base in ["REAL", "FLOAT", "DOUBLE", "DOUBLE PRECISION"] ->
        :float

      base in ["DECIMAL", "NUMERIC"] ->
        :decimal

      base in ["VARCHAR", "CHAR", "CHARACTER", "TEXT", "STRING"] ->
        :string

      base in ["BLOB", "BINARY", "VARBINARY", "BYTEA"] ->
        :binary

      base == "DATE" ->
        :date

      String.starts_with?(base, "TIME") and not String.starts_with?(base, "TIMESTAMP") ->
        :time

      String.starts_with?(base, "TIMESTAMP") or base == "DATETIME" ->
        :datetime

      base == "JSON" ->
        :json

      base == "UUID" ->
        :uuid

      true ->
        :unknown
    end
  end

  defp normalize_grain(nil), do: nil
  defp normalize_grain(%Grain{} = grain), do: Grain.validate!(grain)
  defp normalize_grain(value), do: Grain.new!(value)

  defp normalize_column(%Column{} = column), do: Column.validate!(column)

  defp normalize_column(%{name: name, type: type} = value),
    do:
      Column.new!(name, type,
        null:
          value
          |> Map.get(:opts, [])
          |> Map.new()
          |> Map.get(:null, Map.get(value, :nullable?, Map.get(value, :null, true))),
        description:
          value
          |> Map.get(:opts, [])
          |> Map.new()
          |> Map.get(:description, Map.get(value, :description)),
        renamed_from:
          value
          |> Map.get(:opts, [])
          |> Map.new()
          |> Map.get(:renamed_from, Map.get(value, :renamed_from)),
        tags:
          value |> Map.get(:opts, []) |> Map.new() |> Map.get(:tags, Map.get(value, :tags, [])),
        from:
          value
          |> Map.get(:opts, [])
          |> Map.new()
          |> Map.get(:from, Map.get(value, :sources, Map.get(value, :from, []))),
        via: value |> Map.get(:opts, []) |> Map.new() |> Map.get(:via, Map.get(value, :via))
      )

  defp normalize_column(other),
    do: raise(ArgumentError, "invalid contract column #{inspect(other)}")

  defp normalize_composition(%Composition{} = composition),
    do: Composition.validate!(composition)

  defp normalize_composition(%{module: module, start_index: start_index, columns: columns}),
    do: Composition.new!(module, start_index, columns)

  defp normalize_composition(other),
    do: raise(ArgumentError, "invalid contract composition #{inspect(other)}")

  defp normalize_unique_key(%UniqueKey{} = key), do: UniqueKey.validate!(key)
  defp normalize_unique_key(columns) when is_list(columns), do: UniqueKey.new!(columns)

  defp normalize_unique_key(other),
    do: raise(ArgumentError, "invalid contract unique key #{inspect(other)}")

  defp normalize_row_count(nil), do: nil
  defp normalize_row_count(%RowCount{} = row_count), do: RowCount.validate!(row_count)
  defp normalize_row_count(value), do: RowCount.new!(value)

  defp ensure_unique_columns!(names) do
    case names -- Enum.uniq(names) do
      [] -> :ok
      [name | _rest] -> raise ArgumentError, "duplicate contract column #{inspect(name)}"
    end
  end

  defp ensure_compositions!(compositions, column_names) do
    ensure_unique_composition_modules!(compositions)

    Enum.reduce(compositions, -1, fn composition, previous_end ->
      length = length(composition.columns)
      start_index = composition.start_index
      end_index = start_index + length - 1

      if start_index <= previous_end,
        do: raise(ArgumentError, "contract fragment compositions overlap or are out of order")

      if end_index >= length(column_names),
        do:
          raise(
            ArgumentError,
            "contract fragment #{inspect(composition.module)} extends beyond contract columns"
          )

      actual = Enum.slice(column_names, start_index, length)

      if actual != composition.columns,
        do:
          raise(
            ArgumentError,
            "contract fragment #{inspect(composition.module)} columns do not match the flattened contract at index #{start_index}"
          )

      end_index
    end)

    :ok
  end

  defp ensure_unique_composition_modules!(compositions) do
    modules = Enum.map(compositions, & &1.module)

    case modules -- Enum.uniq(modules) do
      [] -> :ok
      [module | _rest] -> raise ArgumentError, "duplicate contract fragment #{inspect(module)}"
    end
  end

  defp ensure_referenced_columns!(contract, names) do
    references =
      List.wrap(contract.grain && contract.grain.by) ++
        Enum.flat_map(contract.unique_keys, & &1.columns)

    case Enum.find(references, &(not MapSet.member?(names, &1))) do
      nil -> :ok
      name -> raise ArgumentError, "contract key references missing column #{inspect(name)}"
    end
  end

  defp ensure_unique_keys!(keys) do
    normalized = Enum.map(keys, & &1.columns)

    case normalized -- Enum.uniq(normalized) do
      [] ->
        :ok

      [columns | _rest] ->
        raise ArgumentError, "duplicate contract unique key #{inspect(columns)}"
    end
  end

  defp ensure_unique_renames!(columns, current_names) do
    renamed_from = columns |> Enum.map(& &1.renamed_from) |> Enum.reject(&is_nil/1)

    case renamed_from -- Enum.uniq(renamed_from) do
      [] -> :ok
      [name | _rest] -> raise ArgumentError, "duplicate contract renamed_from #{inspect(name)}"
    end

    case Enum.find(renamed_from, &MapSet.member?(current_names, &1)) do
      nil ->
        :ok

      name ->
        raise ArgumentError, "contract renamed_from #{inspect(name)} is still a current column"
    end
  end

  defp ensure_grain_nullability!(%__MODULE__{grain: nil}), do: :ok

  defp ensure_grain_nullability!(%__MODULE__{grain: %Grain{by: []}}), do: :ok

  defp ensure_grain_nullability!(%__MODULE__{} = contract) do
    by_name = Map.new(contract.columns, &{&1.name, &1})

    case Enum.find(contract.grain.by, &Map.fetch!(by_name, &1).nullable?) do
      nil -> :ok
      name -> raise ArgumentError, "contract grain column #{inspect(name)} cannot be nullable"
    end
  end

  defp row_count_specs(%__MODULE__{row_count: nil}), do: []

  defp row_count_specs(%__MODULE__{row_count: row_count}) do
    {claim_id, predicate, metrics, message} = row_count_check(row_count)

    [
      %{
        name: check_name(claim_id),
        claim_id: claim_id,
        at: :before_materialize,
        on_violation: row_count.on_violation,
        when: row_count.when,
        message: message,
        sql:
          "SELECT #{predicate} AS passed, actual#{metrics} " <>
            "FROM (SELECT count(*) AS actual FROM query()) AS favn_contract_row_count"
      }
    ]
  end

  defp row_count_check(%RowCount{equals: %Param{name: name}}) do
    placeholder = "@#{name}"

    {
      "row_count.equals.param.#{name}",
      "actual = #{placeholder}",
      ", #{placeholder} AS expected",
      "Contract row count must equal @#{name}"
    }
  end

  defp row_count_check(%RowCount{equals: equals}) when is_integer(equals) do
    {
      "row_count.equals.literal.#{equals}",
      "actual = #{equals}",
      ", #{equals} AS expected",
      "Contract requires exactly #{equals} rows"
    }
  end

  defp row_count_check(%RowCount{min: min, max: max})
       when is_integer(min) and is_integer(max) do
    {
      "row_count.range.#{min}.#{max}",
      "actual >= #{min} AND actual <= #{max}",
      ", #{min} AS min, #{max} AS max",
      "Contract requires between #{min} and #{max} rows"
    }
  end

  defp row_count_check(%RowCount{min: min}) when is_integer(min) do
    {
      "row_count.min.#{min}",
      "actual >= #{min}",
      ", #{min} AS min",
      "Contract requires at least #{min} rows"
    }
  end

  defp row_count_check(%RowCount{max: max}) when is_integer(max) do
    {
      "row_count.max.#{max}",
      "actual <= #{max}",
      ", #{max} AS max",
      "Contract requires at most #{max} rows"
    }
  end

  defp non_null_specs(%__MODULE__{} = contract) do
    required_columns = Enum.reject(contract.columns, & &1.nullable?)

    case required_columns do
      [] ->
        []

      columns ->
        claim_id = "columns.not_null"
        predicate = Enum.map_join(columns, " OR ", &(quote_identifier(&1.name) <> " IS NULL"))

        [
          %{
            name: check_name(claim_id),
            claim_id: claim_id,
            at: :before_materialize,
            on_violation: :fail,
            when: nil,
            message: "Contract required columns must not contain null values",
            sql:
              "SELECT count(*) = 0 AS passed, count(*) AS invalid_rows " <>
                "FROM query() WHERE #{predicate}"
          }
        ]
    end
  end

  defp unique_specs(%__MODULE__{} = contract) do
    grain_keys =
      case contract.grain do
        %Grain{by: [_first | _rest] = columns} -> [columns]
        _other -> []
      end

    keys = Enum.uniq(grain_keys ++ Enum.map(contract.unique_keys, & &1.columns))

    case keys do
      [] ->
        []

      keys ->
        claim_id = "keys.unique"

        duplicate_queries =
          Enum.map_join(keys, " UNION ALL ", fn columns ->
            grouped = Enum.map_join(columns, ", ", &quote_identifier/1)

            "SELECT count(*) - 1 AS duplicate_count FROM query() " <>
              "GROUP BY #{grouped} HAVING count(*) > 1"
          end)

        [
          %{
            name: check_name(claim_id),
            claim_id: claim_id,
            at: :before_materialize,
            on_violation: :fail,
            when: nil,
            message: "Contract grain and unique keys must be unique",
            sql:
              "SELECT coalesce(sum(duplicate_count), 0) = 0 AS passed, " <>
                "coalesce(sum(duplicate_count), 0) AS duplicate_count " <>
                "FROM (#{duplicate_queries}) AS favn_contract_duplicates"
          }
        ]
    end
  end

  defp validate_generated_check!(%Check{} = check, spec) do
    expected_template =
      Template.compile!(spec.sql,
        file: check.file || "favn_generated_contract_check.sql",
        line: check.line || 1,
        module: nil,
        scope: :query,
        enforce_query_root: true
      )

    matches? =
      check.name == spec.name and
        check.claim_id == spec.claim_id and
        check.at == spec.at and
        check.on_violation == spec.on_violation and
        check.when == spec.when and
        check.message == spec.message and
        check.sql == spec.sql and
        check.template == expected_template and
        check.uses_query? and
        not check.uses_target?

    unless matches?,
      do: raise(ArgumentError, "SQL contract-generated check #{spec.claim_id} was modified")
  end

  defp check_name(claim_id) do
    digest =
      :sha256
      |> :crypto.hash(claim_id)
      |> Base.encode16(case: :lower)
      |> binary_part(0, 16)

    String.to_atom("contract_#{digest}")
  end

  defp quote_identifier(identifier) do
    escaped = identifier |> Atom.to_string() |> String.replace("\"", "\"\"")
    "\"#{escaped}\""
  end
end
